# fly.toml app configuration file generated for workspace-autumn-dew-8172 on 2025-07-25T02:09:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ai-english-chat-owoleq"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
