app = "ai-english-chat"
primary_region = "nrt"

[build]
dockerfile = "./Dockerfile"
context = "."  # 明示的にビルドコンテキストを指定

[env]
PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
